//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Cos.Web.WcfModuleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Com.Cos.WcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfModuleService.IModuleService")]
    public interface IModuleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleService/GetData", ReplyAction="http://tempuri.org/IModuleService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleService/GetData", ReplyAction="http://tempuri.org/IModuleService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IModuleService/GetDataUsingDataContractResponse")]
        Com.Cos.Web.WcfModuleService.CompositeType GetDataUsingDataContract(Com.Cos.Web.WcfModuleService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IModuleService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Com.Cos.Web.WcfModuleService.CompositeType> GetDataUsingDataContractAsync(Com.Cos.Web.WcfModuleService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleService/SingleSendSms", ReplyAction="http://tempuri.org/IModuleService/SingleSendSmsResponse")]
        string SingleSendSms(string signName, string templateCode, string recNum, string paramString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleService/SingleSendSms", ReplyAction="http://tempuri.org/IModuleService/SingleSendSmsResponse")]
        System.Threading.Tasks.Task<string> SingleSendSmsAsync(string signName, string templateCode, string recNum, string paramString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModuleServiceChannel : Com.Cos.Web.WcfModuleService.IModuleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModuleServiceClient : System.ServiceModel.ClientBase<Com.Cos.Web.WcfModuleService.IModuleService>, Com.Cos.Web.WcfModuleService.IModuleService {
        
        public ModuleServiceClient() {
        }
        
        public ModuleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModuleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Com.Cos.Web.WcfModuleService.CompositeType GetDataUsingDataContract(Com.Cos.Web.WcfModuleService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Com.Cos.Web.WcfModuleService.CompositeType> GetDataUsingDataContractAsync(Com.Cos.Web.WcfModuleService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string SingleSendSms(string signName, string templateCode, string recNum, string paramString) {
            return base.Channel.SingleSendSms(signName, templateCode, recNum, paramString);
        }
        
        public System.Threading.Tasks.Task<string> SingleSendSmsAsync(string signName, string templateCode, string recNum, string paramString) {
            return base.Channel.SingleSendSmsAsync(signName, templateCode, recNum, paramString);
        }
    }
}
